export const mockContacts = [
  {
    id: '1',
    firstName: 'John',
    lastName: 'Doe',
    phone: '123-456-7890',
    email: 'john.doe@example.com',
    address: '123 Main St, Anytown, USA',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    id: '2',
    firstName: 'Jane',
    lastName: 'Smith',
    phone: '987-654-3210',
    email: 'jane.smith@example.com',
    address: '456 Oak St, Another Town, USA',
    notes: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    id: '3',
    firstName: 'Alice',
    lastName: 'Johnson',
    phone: '555-123-4567',
    email: 'alice.johnson@example.com',
    address: '789 Elm St, Yet Another Town, USA',
    notes:
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  },
  {
    id: '4',
    firstName: 'Bob',
    lastName: 'Brown',
    phone: '444-555-6666',
    email: 'bob.brown@example.com',
    address: '321 Pine St, Some City, USA',
    notes:
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
  },
  {
    id: '5',
    firstName: 'Emily',
    lastName: 'Davis',
    phone: '777-888-9999',
    email: 'emily.davis@example.com',
    address: '987 Cedar St, A Different City, USA',
    notes:
      'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: '6',
    firstName: 'Michael',
    lastName: 'Wilson',
    phone: '333-222-1111',
    email: 'michael.wilson@example.com',
    address: '555 Maple St, My Town, USA',
    notes:
      'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
  },
  {
    id: '7',
    firstName: 'Sarah',
    lastName: 'Martinez',
    phone: '111-222-3333',
    email: 'sarah.martinez@example.com',
    address: '222 Birch St, Their Town, USA',
    notes:
      'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.',
  },
  {
    id: '8',
    firstName: 'David',
    lastName: 'Anderson',
    phone: '666-777-8888',
    email: 'david.anderson@example.com',
    address: '888 Walnut St, Our Town, USA',
    notes:
      'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
  },
  {
    id: '9',
    firstName: 'Laura',
    lastName: 'Garcia',
    phone: '222-333-4444',
    email: 'laura.garcia@example.com',
    address: '777 Spruce St, Some Other City, USA',
    notes:
      'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
  },
  {
    id: '10',
    firstName: 'Kevin',
    lastName: 'Rodriguez',
    phone: '888-999-0000',
    email: 'kevin.rodriguez@example.com',
    address: '666 Oak St, Another City, USA',
    notes: 'Et harum quidem rerum facilis est et expedita distinctio.',
  },
  {
    id: '11',
    firstName: 'Daniel',
    lastName: 'Young',
    phone: '444-555-6666',
    email: 'daniel.young@example.com',
    address: '444 Maple St, Countryside, USA',
    notes:
      'Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.',
  },
  {
    id: '12',
    firstName: 'Jennifer',
    lastName: 'Hill',
    phone: '555-666-7777',
    email: 'jennifer.hill@example.com',
    address: '555 Pine St, Townsville, USA',
    notes:
      'Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
  },
  {
    id: '13',
    firstName: 'Ryan',
    lastName: 'Carter',
    phone: '666-777-8888',
    email: 'ryan.carter@example.com',
    address: '666 Elm St, Suburbia, USA',
    notes:
      'Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt.',
  },
  {
    id: '14',
    firstName: 'Melissa',
    lastName: 'King',
    phone: '777-888-9999',
    email: 'melissa.king@example.com',
    address: '777 Oak St, Hamlet, USA',
    notes:
      'Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit.',
  },
  {
    id: '15',
    firstName: 'Christopher',
    lastName: 'Lee',
    phone: '888-999-0000',
    email: 'christopher.lee@example.com',
    address: '888 Maple St, Riverside, USA',
    notes:
      'Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.',
  },
  {
    id: '16',
    firstName: 'Megan',
    lastName: 'Parker',
    phone: '999-000-1111',
    email: 'megan.parker@example.com',
    address: '999 Elm St, Lakeside, USA',
    notes:
      'At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga.',
  },
  {
    id: '17',
    firstName: 'Nicholas',
    lastName: 'Wright',
    phone: '000-111-2222',
    email: 'nicholas.wright@example.com',
    address: '000 Pine St, Lakeshore, USA',
    notes: 'Et harum quidem rerum facilis est et expedita distinctio.',
  },
  {
    id: '18',
    firstName: 'Stephanie',
    lastName: 'Adams',
    phone: '111-222-3333',
    email: 'stephanie.adams@example.com',
    address: '111 Oak St, Mountainview, USA',
    notes: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
  },
  {
    id: '19',
    firstName: 'Justin',
    lastName: 'Cook',
    phone: '222-333-4444',
    email: 'justin.cook@example.com',
    address: '222 Elm St, Beachside, USA',
    notes: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
  },
  {
    id: '20',
    firstName: 'Nicole',
    lastName: 'Baker',
    phone: '333-444-5555',
    email: 'nicole.baker@example.com',
    address: '333 Maple St, Countryside, USA',
    notes:
      'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
  },
]
